language: python
dist: xenial
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -U pip wheel setuptools
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script:
  - isort -c --skip-glob=venv
  - flake8 tests/ validate_email/ setup.py
  - python -m unittest discover -v
